# Generated by Django 5.0.7 on 2024-07-22 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentfavorite',
            name='blog',
        ),
        migrations.AddField(
            model_name='commentfavorite',
            name='like_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='likes_comment', to='comments.comment'),
            preserve_default=False,
        ),
    ]
